In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
data_tensor = torch.tensor(data)
print(data_tensor, type(data_tensor))

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) <class 'torch.Tensor'>


In [3]:
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np_data = np.array(data)
print(np_data, type(np_data))
np_data_tensor = torch.tensor(np_data)
print(np_data_tensor, type(np_data_tensor))

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) <class 'torch.Tensor'>


In [4]:
torch.zeros(5)

tensor([0., 0., 0., 0., 0.])

In [5]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [6]:
torch.ones(3,3,3)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [7]:
zero_tensor = torch.zeros(3,3)
ones_like_zeroes = torch.ones_like(zero_tensor)

print(zero_tensor.shape, ones_like_zeroes.shape)

torch.Size([3, 3]) torch.Size([3, 3])


In [8]:
zero_tensor[0]

tensor([0., 0., 0.])

In [9]:
zero_tensor[0][0]

tensor(0.)

In [10]:
ones_like_zeroes[:,0]

tensor([1., 1., 1.])

In [11]:
x = ones_like_zeroes.detach()
#creates a copy that is detached from the tensor, does not affect the graph
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [12]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [13]:
x[:,0]

tensor([1., 1., 1.])

In [14]:
rand1 = torch.rand(5)
rand2 = torch.rand(5)
torch.matmul(rand1, rand2)

tensor(0.9752)

In [15]:
rand1 = torch.rand(3, 3)
rand2 = torch.rand(3, 3)
torch.matmul(rand1, rand2)

tensor([[1.4384, 1.3416, 1.7077],
        [0.8685, 0.6482, 0.8261],
        [1.4034, 1.2615, 1.5559]])